---
pipeline:
  test:
      image: digitalpatterns/node:latest
      commands:
        - yum install -y libX11-devel libX11-common libXcomposite libXcursor libXdamage libXext libXi libXtst cups-libs libXScrnSaver libXrandr alsa-lib atk at-spi2-atk cairo pango gtk3 java-1.8.0-openjdk
        - npm install
        - npm run build-ts
        - npm run test
      when:
        event:
        - push
        - pull_request

  build_push_to_ecr:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
    - source: DEV_PDF_GENERATOR_AWS_ACCESS_KEY_ID
      target: AWS_ACCESS_KEY_ID
    - source: DEV_PDF_GENERATOR_AWS_SECRET_ACCESS_KEY
      target: AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/cop/pdf-generator
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_PROTOCOL
      - DEV_PDF_GENERATOR_NAME
      - DEV_PDF_GENERATOR_IMAGE
      - DEV_PDF_GENERATOR_KEYCLOAK_CLIENT_ID
      - DEV_PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET
      - DEV_PDF_GENERATOR_KUBE_NAMESPACE
      - DEV_PDF_GENERATOR_AWS_ACCESS_KEY_ID
      - DEV_PDF_GENERATOR_AWS_SECRET_ACCESS_KEY
      - DEV_PDF_GENERATOR_PORT
      - DEV_PDF_GENERATOR_KEYCLOAK_SESSION_SECRET
      - DEV_PDF_GENERATOR_ARENA_ACCESS_ROLES
      - DEV_PDF_GENERATOR_LOG_LEVEL
      - DEV_PDF_GENERATOR_AWS_S3_ENDPOINT
      - DEV_PDF_GENERATOR_AWS_S3_PORT
      - DEV_PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME
      - DEV_PDF_GENERATOR_AWS_S3_ACCESS_KEY
      - DEV_PDF_GENERATOR_AWS_S3_SECRET_KEY
      - DEV_PDF_GENERATOR_AWS_S3_PROTOCOL
      - DEV_PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER
      - DEV_NGINX_IMAGE
      - DEV_NGINX_TAG
    commands:
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${DEV_PDF_GENERATOR_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${DEV_KEYCLOAK_PROTOCOL}
      - export PDF_GENERATOR_NAME=$${DEV_PDF_GENERATOR_NAME}
      - export PDF_GENERATOR_IMAGE=$${DEV_PDF_GENERATOR_IMAGE}
      - export PDF_GENERATOR_KEYCLOAK_CLIENT_ID=$${DEV_PDF_GENERATOR_KEYCLOAK_CLIENT_ID}
      - export PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET=$${DEV_PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET}
      - export PDF_GENERATOR_KEYCLOAK_SESSION_SECRET=$${DEV_PDF_GENERATOR_KEYCLOAK_SESSION_SECRET}
      - export PDF_GENERATOR_ARENA_ACCESS_ROLES=$${DEV_PDF_GENERATOR_ARENA_ACCESS_ROLES}
      - export PDF_GENERATOR_KUBE_NAMESPACE=$${DEV_PDF_GENERATOR_KUBE_NAMESPACE}
      - export PDF_GENERATOR_AWS_ACCESS_KEY_ID=$${DEV_PDF_GENERATOR_AWS_ACCESS_KEY_ID}
      - export PDF_GENERATOR_AWS_SECRET_ACCESS_KEY=$${DEV_PDF_GENERATOR_AWS_SECRET_ACCESS_KEY}
      - export PDF_GENERATOR_LOG_LEVEL=$${DEV_PDF_GENERATOR_LOG_LEVEL}
      - export PDF_GENERATOR_AWS_S3_ENDPOINT=$${DEV_PDF_GENERATOR_AWS_S3_ENDPOINT}
      - export PDF_GENERATOR_AWS_S3_PORT=$${DEV_PDF_GENERATOR_AWS_S3_PORT}
      - export PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME=$${DEV_PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME}
      - export PDF_GENERATOR_AWS_S3_ACCESS_KEY=$${DEV_PDF_GENERATOR_AWS_S3_ACCESS_KEY}
      - export PDF_GENERATOR_AWS_S3_SECRET_KEY=$${DEV_PDF_GENERATOR_AWS_S3_SECRET_KEY}
      - export PDF_GENERATOR_AWS_S3_PROTOCOL=$${DEV_PDF_GENERATOR_AWS_S3_PROTOCOL}
      - export PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER=$${DEV_PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER}
      - export NGINX_IMAGE=$${DEV_NGINX_IMAGE}
      - export NGINX_TAG=$${DEV_NGINX_TAG}
      - export PDF_GENERATOR_PORT=$${DEV_PDF_GENERATOR_PORT}
      - export PDF_GENERATOR_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_KEYCLOAK_URL
      - STAGING_KEYCLOAK_REALM
      - STAGING_KEYCLOAK_PROTOCOL
      - STAGING_PDF_GENERATOR_NAME
      - STAGING_PDF_GENERATOR_IMAGE
      - STAGING_PDF_GENERATOR_KEYCLOAK_CLIENT_ID
      - STAGING_PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET
      - STAGING_PDF_GENERATOR_KUBE_NAMESPACE
      - STAGING_PDF_GENERATOR_AWS_ACCESS_KEY_ID
      - STAGING_PDF_GENERATOR_AWS_SECRET_ACCESS_KEY
      - STAGING_PDF_GENERATOR_PORT
      - STAGING_PDF_GENERATOR_KEYCLOAK_SESSION_SECRET
      - STAGING_PDF_GENERATOR_ARENA_ACCESS_ROLES
      - STAGING_PDF_GENERATOR_LOG_LEVEL
      - STAGING_PDF_GENERATOR_AWS_S3_ENDPOINT
      - STAGING_PDF_GENERATOR_AWS_S3_PORT
      - STAGING_PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME
      - STAGING_PDF_GENERATOR_AWS_S3_ACCESS_KEY
      - STAGING_PDF_GENERATOR_AWS_S3_SECRET_KEY
      - STAGING_PDF_GENERATOR_AWS_S3_PROTOCOL
      - STAGING_PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER
      - STAGING_NGINX_IMAGE
      - STAGING_NGINX_TAG
    commands:
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${STAGING_PDF_GENERATOR_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${STAGING_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${STAGING_KEYCLOAK_PROTOCOL}
      - export PDF_GENERATOR_NAME=$${STAGING_PDF_GENERATOR_NAME}
      - export PDF_GENERATOR_IMAGE=$${STAGING_PDF_GENERATOR_IMAGE}
      - export PDF_GENERATOR_KEYCLOAK_CLIENT_ID=$${STAGING_PDF_GENERATOR_KEYCLOAK_CLIENT_ID}
      - export PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET=$${STAGING_PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET}
      - export PDF_GENERATOR_KEYCLOAK_SESSION_SECRET=$${STAGING_PDF_GENERATOR_KEYCLOAK_SESSION_SECRET}
      - export PDF_GENERATOR_ARENA_ACCESS_ROLES=$${STAGING_PDF_GENERATOR_ARENA_ACCESS_ROLES}
      - export PDF_GENERATOR_KUBE_NAMESPACE=$${STAGING_PDF_GENERATOR_KUBE_NAMESPACE}
      - export PDF_GENERATOR_AWS_ACCESS_KEY_ID=$${STAGING_PDF_GENERATOR_AWS_ACCESS_KEY_ID}
      - export PDF_GENERATOR_AWS_SECRET_ACCESS_KEY=$${STAGING_PDF_GENERATOR_AWS_SECRET_ACCESS_KEY}
      - export PDF_GENERATOR_LOG_LEVEL=$${STAGING_PDF_GENERATOR_LOG_LEVEL}
      - export PDF_GENERATOR_AWS_S3_ENDPOINT=$${STAGING_PDF_GENERATOR_AWS_S3_ENDPOINT}
      - export PDF_GENERATOR_AWS_S3_PORT=$${STAGING_PDF_GENERATOR_AWS_S3_PORT}
      - export PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME=$${STAGING_PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME}
      - export PDF_GENERATOR_AWS_S3_ACCESS_KEY=$${STAGING_PDF_GENERATOR_AWS_S3_ACCESS_KEY}
      - export PDF_GENERATOR_AWS_S3_SECRET_KEY=$${STAGING_PDF_GENERATOR_AWS_S3_SECRET_KEY}
      - export PDF_GENERATOR_AWS_S3_PROTOCOL=$${STAGING_PDF_GENERATOR_AWS_S3_PROTOCOL}
      - export PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER=$${STAGING_PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER}
      - export NGINX_IMAGE=$${STAGING_NGINX_IMAGE}
      - export NGINX_TAG=$${STAGING_NGINX_TAG}
      - export PDF_GENERATOR_PORT=$${STAGING_PDF_GENERATOR_PORT}
      - export PDF_GENERATOR_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
    when:
      environment: staging
      branch: master
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_KEYCLOAK_URL
      - PRODUCTION_KEYCLOAK_REALM
      - PRODUCTION_KEYCLOAK_PROTOCOL
      - PRODUCTION_PDF_GENERATOR_NAME
      - PRODUCTION_PDF_GENERATOR_IMAGE
      - PRODUCTION_PDF_GENERATOR_KEYCLOAK_CLIENT_ID
      - PRODUCTION_PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET
      - PRODUCTION_PDF_GENERATOR_KUBE_NAMESPACE
      - PRODUCTION_PDF_GENERATOR_AWS_ACCESS_KEY_ID
      - PRODUCTION_PDF_GENERATOR_AWS_SECRET_ACCESS_KEY
      - PRODUCTION_PDF_GENERATOR_PORT
      - PRODUCTION_PDF_GENERATOR_KEYCLOAK_SESSION_SECRET
      - PRODUCTION_PDF_GENERATOR_ARENA_ACCESS_ROLES
      - PRODUCTION_PDF_GENERATOR_LOG_LEVEL
      - PRODUCTION_PDF_GENERATOR_AWS_S3_ENDPOINT
      - PRODUCTION_PDF_GENERATOR_AWS_S3_PORT
      - PRODUCTION_PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME
      - PRODUCTION_PDF_GENERATOR_AWS_S3_ACCESS_KEY
      - PRODUCTION_PDF_GENERATOR_AWS_S3_SECRET_KEY
      - PRODUCTION_PDF_GENERATOR_AWS_S3_PROTOCOL
      - PRODUCTION_PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER
      - PRODUCTION_NGINX_IMAGE
      - PRODUCTION_NGINX_TAG
    commands:
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${PRODUCTION_PDF_GENERATOR_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${PRODUCTION_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${PRODUCTION_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${PRODUCTION_KEYCLOAK_PROTOCOL}
      - export PDF_GENERATOR_NAME=$${PRODUCTION_PDF_GENERATOR_NAME}
      - export PDF_GENERATOR_IMAGE=$${PRODUCTION_PDF_GENERATOR_IMAGE}
      - export PDF_GENERATOR_KEYCLOAK_CLIENT_ID=$${PRODUCTION_PDF_GENERATOR_KEYCLOAK_CLIENT_ID}
      - export PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET=$${PRODUCTION_PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET}
      - export PDF_GENERATOR_KEYCLOAK_SESSION_SECRET=$${PRODUCTION_PDF_GENERATOR_KEYCLOAK_SESSION_SECRET}
      - export PDF_GENERATOR_ARENA_ACCESS_ROLES=$${PRODUCTION_PDF_GENERATOR_ARENA_ACCESS_ROLES}
      - export PDF_GENERATOR_KUBE_NAMESPACE=$${PRODUCTION_PDF_GENERATOR_KUBE_NAMESPACE}
      - export PDF_GENERATOR_AWS_ACCESS_KEY_ID=$${PRODUCTION_PDF_GENERATOR_AWS_ACCESS_KEY_ID}
      - export PDF_GENERATOR_AWS_SECRET_ACCESS_KEY=$${PRODUCTION_PDF_GENERATOR_AWS_SECRET_ACCESS_KEY}
      - export PDF_GENERATOR_LOG_LEVEL=$${PRODUCTION_PDF_GENERATOR_LOG_LEVEL}
      - export PDF_GENERATOR_AWS_S3_ENDPOINT=$${PRODUCTION_PDF_GENERATOR_AWS_S3_ENDPOINT}
      - export PDF_GENERATOR_AWS_S3_PORT=$${PRODUCTION_PDF_GENERATOR_AWS_S3_PORT}
      - export PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME=$${PRODUCTION_PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME}
      - export PDF_GENERATOR_AWS_S3_ACCESS_KEY=$${PRODUCTION_PDF_GENERATOR_AWS_S3_ACCESS_KEY}
      - export PDF_GENERATOR_AWS_S3_SECRET_KEY=$${PRODUCTION_PDF_GENERATOR_AWS_S3_SECRET_KEY}
      - export PDF_GENERATOR_AWS_S3_PROTOCOL=$${PRODUCTION_PDF_GENERATOR_AWS_S3_PROTOCOL}
      - export PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER=$${PRODUCTION_PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER}
      - export NGINX_IMAGE=$${PRODUCTION_NGINX_IMAGE}
      - export NGINX_TAG=$${PRODUCTION_NGINX_TAG}
      - export PDF_GENERATOR_PORT=$${PRODUCTION_PDF_GENERATOR_PORT}
      - export PDF_GENERATOR_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
    when:
      environment: production
      branch: master
      event: deployment

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
