---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.PDF_GENERATOR_NAME}}"
spec:
  selector:
    matchLabels:
      name: "{{.PDF_GENERATOR_NAME}}"
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: "{{.PDF_GENERATOR_NAME}}"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: "{{.DOCKER_CREDENTIALS}}"
      containers:
      - name: proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.PDF_GENERATOR_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: "{{.PDF_GENERATOR_NAME}}"
        image: "{{.PDF_GENERATOR_IMAGE}}:{{.PDF_GENERATOR_TAG}}"
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{.PDF_GENERATOR_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: {{.PDF_GENERATOR_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
          - name: KEYCLOAK_URI
            value: "{{.KEYCLOAK_PROTOCOL}}{{.KEYCLOAK_URL}}"
          - name: KEYCLOAK_REALM
            value: "{{.KEYCLOAK_REALM}}"
          - name: PDF_GENERATOR_KEYCLOAK_CLIENT_ID
            value: "{{.PDF_GENERATOR_KEYCLOAK_CLIENT_ID}}"
          - name: PDF_GENERATOR_ARENA_ACCESS_ROLES
            value: "{{.PDF_GENERATOR_ARENA_ACCESS_ROLES}}"
          - name: PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{.PDF_GENERATOR_NAME}}"
                key: keycloakClientSecret
          - name: PDF_GENERATOR_PORT
            value: "{{.PDF_GENERATOR_PORT}}"
          - name: PDF_GENERATOR_LOG_LEVEL
            value: "{{.PDF_GENERATOR_LOG_LEVEL}}"
          - name: PDF_GENERATOR_AWS_S3_ENDPOINT
            value: "{{.PDF_GENERATOR_AWS_S3_ENDPOINT}}"
          - name: PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME
            value: "{{.PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME}}"
          - name: PDF_GENERATOR_AWS_S3_ACCESS_KEY
            value: "{{.PDF_GENERATOR_AWS_S3_ACCESS_KEY}}"
          - name: PDF_GENERATOR_AWS_S3_PORT
            value: "{{.PDF_GENERATOR_AWS_S3_PORT}}"
          - name: PDF_GENERATOR_AWS_S3_PROTOCOL
            value: "{{.PDF_GENERATOR_AWS_S3_PROTOCOL}}"
          - name: PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER
            value: "{{.PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER}}"
          - name: PDF_GENERATOR_AWS_S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "{{.PDF_GENERATOR_NAME}}"
                key: awsS3SecretKey
          - name: REDIS_PORT
            value: "{{.REDIS_PORT}}"
          - name: REDIS_SSL
            value: "{{.REDIS_SSL}}"
          - name: REDIS_URI
            value: "{{.REDIS_URL}}"
          - name: REDIS_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{.PDF_GENERATOR_NAME}}"
                key: redisToken
      volumes:
      - name: certs
        secret:
          secretName: "{{.PDF_GENERATOR_NAME}}-pod-tls"
