apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.PDF_GENERATOR_NAME}}
spec:
  podSelector:
    matchLabels:
      name: {{.PDF_GENERATOR_NAME}}
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - port: 10443
      protocol: TCP
